version: "3.9"
services:
    rust-web-service-api:
        build: ./docker/development
        container_name: "cargo-watch-example"
        volumes:
            - .:/app
        command: sh -c "cargo watch -x run"